# HPC & configs lists to be tested with SETTE
.parallel_HPC_CFG:
  parallel:
    matrix:
      - HPC: [irene,jean-zay]
        CONFIG: [ORCA2_ICE_PISCES,ORCA2_OFF_PISCES,AMM12,AGRIF_DEMO,WED025,GYRE_PISCES,GYRE_GO,ORCA2_SAS_ICE,ORCA2_ICE_OBS,C1D_PAPA]

# HPC & testcases lists to be tested with SETTE
.parallel_HPC_TST:
  parallel:
    matrix:
      - HPC: [irene,jean-zay]
        CONFIG: [SWG,ICE_AGRIF,OVERFLOW,LOCK_EXCHANGE,VORTEX,ISOMIP+,IWAVE]


# variables declared hereafter will be avaible in all jobs
# these 2 variables are needed for each HPC to be tested:
# - SETTE_CFG: SETTE param.cfg file path
# - SETTE_MOD: SETTE modules list -> not needed anymore with new ".env" files

variables:
  # JEAN-ZAY
  JZ_SETTE_CFG: "/linkhome/rech/genloc01/reee217/nemo_CI/param.cfg"
  JZ_SETTE_MOD: "intel-compilers/19.1.3 intel-mpi/2019.9 hdf5/1.12.0-mpi netcdf-c/4.7.4-mpi netcdf-fortran/4.5.3-mpi git/2.25.0"
  # IRENE
  IR_SETTE_CFG: "/ccc/cont005/dsku/leger/home/user/locean/massons/nemo_CI/param.cfg"
  IR_SETTE_MOD: "intel/19.0.5.281 mpi/openmpi/4.0.2 flavor/hdf5/parallel flavor/buildmpi/openmpi/4.0 netcdf-c/4.6.0 netcdf-fortran/4.4.4 hdf5/1.8.20 boost/1.69.0 blitz/0.10 c++/gnu/7.3.0 c/gnu/7.3.0"
